import { useEffect, useMemo, useState } from "react";
import {
  Plug, CheckCircle2, XCircle, AlertTriangle, Loader2, RefreshCw, Power,
  ExternalLink, Save, ShieldCheck, Activity, Trash2, Eye, EyeOff,
  Copy, Check, Webhook, Info,
} from "lucide-react";
import { IntegrationUrlsDocModal } from "@/components/admin/IntegrationUrlsDocModal";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { showErrorToast, showSuccessToast } from "@/lib/toast";
import { api } from "@/lib/api";
import { API_BASE_URL, SITE_URL } from "@/config/constants";
import { AdminPageHeader } from "@/components/admin/AdminPageHeader";
import { useConfirm } from "@/components/ConfirmDialog";
import quickbooksLogo from "@/assets/integrations/quickbooks.png";
import amazonLogo from "@/assets/integrations/amazon.png";
import ebayLogo from "@/assets/integrations/ebay.png";

type ProviderId = "quickbooks" | "amazon" | "ebay";

function canonicalAppBaseUrl(): string {
  // OAuth redirect URIs must point to the public frontend (e.g. https://www.remquip.ca),
  // NOT the backend host. Prefer VITE_PUBLIC_APP_URL, then SITE_URL, then current origin.
  const envUrl = (typeof import.meta.env.VITE_PUBLIC_APP_URL === "string"
    ? import.meta.env.VITE_PUBLIC_APP_URL
    : "").trim().replace(/\/+$/, "");
  if (envUrl) return envUrl;
  if (SITE_URL) return SITE_URL.replace(/\/+$/, "");
  if (typeof window !== "undefined" && window.location?.origin) return window.location.origin;
  return "";
}

function oauthCallbackUrl(providerId: ProviderId): string {
  return `${canonicalAppBaseUrl()}/admin/integrations/oauth/${providerId}`;
}

const PROVIDER_LOGOS: Record<ProviderId, string> = {
  quickbooks: quickbooksLogo,
  amazon: amazonLogo,
  ebay: ebayLogo,
};
type Status = "disconnected" | "pending" | "connected" | "error";

interface Integration {
  id: string;
  provider: ProviderId;
  display_name: string;
  environment: "sandbox" | "production";
  status: Status;
  is_enabled: 0 | 1 | boolean;
  connected_at: string | null;
  last_sync_at: string | null;
  last_error: string | null;
  token_expires_at: string | null;
  config: Record<string, any>;
  credentials?: Record<string, any>;
  has_credentials?: boolean;
}

interface IntegrationLog {
  id: string;
  action: string;
  status: "success" | "error" | "warning" | "info";
  message: string | null;
  items_processed: number | null;
  items_failed: number | null;
  duration_ms: number | null;
  created_at: string;
}

interface OAuthStartResponse {
  authorize_url: string;
  state?: string;
}

interface ProviderMeta {
  id: ProviderId;
  name: string;
  tagline: string;
  brandColor: string;
  docsUrl: string;
  fields: { key: string; label: string; secret?: boolean; placeholder?: string; helper?: string }[];
  capabilities: { key: string; label: string }[];
  syncEntities: { key: string; label: string }[];
}

const PROVIDERS: ProviderMeta[] = [
  {
    id: "quickbooks",
    name: "QuickBooks Online",
    tagline: "Sync customers, invoices, payments and items with QuickBooks Online (Intuit OAuth 2.0).",
    brandColor: "hsl(142 70% 35%)",
    docsUrl: "https://developer.intuit.com/app/developer/qbo/docs/get-started",
    fields: [
      { key: "client_id",     label: "Client ID",     placeholder: "Q0...", helper: "From your Intuit App → Keys & OAuth" },
      { key: "client_secret", label: "Client Secret", secret: true },
      { key: "realm_id",      label: "Realm ID (Company ID)", placeholder: "1234567890" },
      { key: "redirect_uri",  label: "Redirect URI",  placeholder: "https://yourdomain.com/admin/integrations/oauth/quickbooks", helper: "Must match the OAuth Redirect URI shown in the Webhooks tab exactly." },
      { key: "access_token",  label: "Access Token",  secret: true, helper: "Captured automatically after OAuth callback" },
      { key: "refresh_token", label: "Refresh Token", secret: true },
      { key: "webhook_verifier_token", label: "Webhook Verifier Token", secret: true, helper: "Generated by Intuit when you save the webhook URL. Required for HMAC-SHA256 signature checks." },
    ],
    capabilities: [
      { key: "sync_customers", label: "Customers ↔ QBO Customers" },
      { key: "sync_invoices",  label: "Invoices → QBO Invoices" },
      { key: "sync_payments",  label: "Payments → QBO Payments" },
      { key: "sync_products",  label: "Products ↔ QBO Items" },
    ],
    syncEntities: [
      { key: "customers", label: "Customers" },
      { key: "invoices",  label: "Invoices" },
      { key: "products",  label: "Items / Products" },
    ],
  },
  {
    id: "amazon",
    name: "Amazon Seller Central",
    tagline: "Push listings, pull orders & inventory using Amazon SP-API (LWA + IAM).",
    brandColor: "hsl(35 95% 50%)",
    docsUrl: "https://developer-docs.amazon.com/sp-api/docs/welcome",
    fields: [
      { key: "lwa_client_id",     label: "LWA Client ID",     placeholder: "amzn1.application-oa2-client...." },
      { key: "lwa_client_secret", label: "LWA Client Secret", secret: true },
      { key: "refresh_token",     label: "Refresh Token",     secret: true, helper: "From the Seller authorization workflow" },
      { key: "seller_id",         label: "Seller ID",         placeholder: "A1B2C3D4E5F6G7" },
      { key: "marketplace_id",    label: "Marketplace ID",    placeholder: "ATVPDKIKX0DER (US)" },
      { key: "aws_access_key",    label: "AWS Access Key (optional)" },
      { key: "aws_secret_key",    label: "AWS Secret Key (optional)", secret: true },
      { key: "role_arn",          label: "IAM Role ARN (optional)" },
    ],
    capabilities: [
      { key: "sync_listings",  label: "Push product listings" },
      { key: "sync_orders",    label: "Pull orders into Remquip" },
      { key: "sync_inventory", label: "Two-way inventory sync" },
    ],
    syncEntities: [
      { key: "listings",  label: "Listings" },
      { key: "orders",    label: "Orders" },
      { key: "inventory", label: "Inventory" },
    ],
  },
  {
    id: "ebay",
    name: "eBay Marketplace",
    tagline: "List products and ingest orders from eBay using the Sell APIs (OAuth 2.0).",
    brandColor: "hsl(214 100% 45%)",
    docsUrl: "https://developer.ebay.com/api-docs/static/oauth-tokens.html",
    fields: [
      { key: "app_id",        label: "App ID (Client ID)", placeholder: "Yourapp-Production-..." },
      { key: "cert_id",       label: "Cert ID (Client Secret)", secret: true },
      { key: "dev_id",        label: "Dev ID" },
      { key: "redirect_uri",  label: "RuName / Redirect URI" },
      { key: "refresh_token", label: "User Refresh Token", secret: true, helper: "From the user consent flow (offline_access scope)" },
      { key: "marketplace_id", label: "Marketplace (e.g. EBAY_US)" },
      { key: "webhook_verification_token", label: "Webhook Verification Token", secret: true, helper: "Required for the marketplace account deletion challenge & x-ebay-signature checks. 32-80 chars, store the same value here and in eBay Developer Console." },
    ],
    capabilities: [
      { key: "sync_listings",  label: "Push listings to eBay" },
      { key: "sync_orders",    label: "Pull eBay orders" },
      { key: "sync_inventory", label: "Inventory sync" },
    ],
    syncEntities: [
      { key: "listings",  label: "Listings" },
      { key: "orders",    label: "Orders" },
      { key: "inventory", label: "Inventory" },
    ],
  },
];

function statusBadge(status: Status) {
  const map: Record<Status, { variant: any; icon: any; label: string }> = {
    connected:    { variant: "default",     icon: CheckCircle2,   label: "Connected" },
    disconnected: { variant: "secondary",   icon: XCircle,        label: "Disconnected" },
    pending:      { variant: "outline",     icon: Loader2,        label: "Pending" },
    error:        { variant: "destructive", icon: AlertTriangle,  label: "Error" },
  };
  const cfg = map[status] ?? map.disconnected;
  const Icon = cfg.icon;
  return (
    <Badge variant={cfg.variant} className="gap-1">
      <Icon className={`h-3 w-3 ${status === "pending" ? "animate-spin" : ""}`} />
      {cfg.label}
    </Badge>
  );
}

export default function AdminIntegrations() {
  const [integrations, setIntegrations] = useState<Integration[]>([]);
  const [loading, setLoading] = useState(true);
  const [openProvider, setOpenProvider] = useState<ProviderId | null>(null);
  const [busy, setBusy] = useState<string | null>(null);
  const [docsOpen, setDocsOpen] = useState(false);
  const confirm = useConfirm();

  // Auto-open the URL documentation modal on first visit per browser.
  useEffect(() => {
    try {
      const seen = localStorage.getItem("remquip:integrations:urls-doc-seen");
      if (!seen) {
        setDocsOpen(true);
        localStorage.setItem("remquip:integrations:urls-doc-seen", "1");
      }
    } catch {
      /* ignore storage errors */
    }
  }, []);

  const load = async () => {
    try {
      setLoading(true);
      const res = await api.request<Integration[]>("GET", "integrations");
      setIntegrations((res.data as Integration[]) ?? []);
    } catch (e: any) {
      showErrorToast(e?.message || "Failed to load integrations");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { load(); }, []);

  const byProvider = useMemo(() => {
    const m: Record<string, Integration | undefined> = {};
    integrations.forEach((it) => { m[it.provider] = it; });
    return m;
  }, [integrations]);

  const runAction = async (provider: ProviderId, action: "connect" | "disconnect" | "test", body?: any) => {
    try {
      setBusy(`${provider}:${action}`);
      const res = await api.request("POST", `integrations/${provider}/${action}`, body);
      showSuccessToast(res.message || `${action} OK`);
      await load();
    } catch (e: any) {
      showErrorToast(e?.message || `${action} failed`);
    } finally {
      setBusy(null);
    }
  };

  const startOAuth = async (provider: ProviderId) => {
    try {
      setBusy(`${provider}:oauth`);
      // Always use the canonical app URL derived from API_BASE_URL, not the Lovable preview origin.
      // Intuit rejects preview/staging URLs unless they are separately whitelisted.
      const canonicalRedirectUri = oauthCallbackUrl(provider);
      const saved = byProvider[provider]?.credentials?.redirect_uri as string | undefined;
      const redirectUri = saved && saved === canonicalRedirectUri ? saved : canonicalRedirectUri;
      const qs = `?redirect_uri=${encodeURIComponent(redirectUri)}`;
      const res = await api.request<OAuthStartResponse>("GET", `integrations/${provider}/oauth/start${qs}`);
      const authorizeUrl = (res.data as OAuthStartResponse | undefined)?.authorize_url;
      if (!authorizeUrl) throw new Error("QuickBooks did not return an authorization URL.");
      window.location.assign(authorizeUrl);
    } catch (e: any) {
      showErrorToast(e?.message || "Failed to start QuickBooks authorization");
      setBusy(null);
    }
  };

  const triggerSync = async (provider: ProviderId, entity: string) => {
    try {
      setBusy(`${provider}:sync:${entity}`);
      await api.request("POST", `integrations/${provider}/sync`, { entity });
      showSuccessToast(`Sync queued for ${entity}`);
      await load();
    } catch (e: any) {
      showErrorToast(e?.message || "Sync failed");
    } finally {
      setBusy(null);
    }
  };

  return (
    <div className="space-y-6">
      <AdminPageHeader
        title="Integrations"
        subtitle="Connect Remquip with QuickBooks, Amazon and eBay. Enter API credentials, then connect & sync."
        actions={
          <div className="flex items-center gap-2">
            <Button size="sm" variant="outline" onClick={() => setDocsOpen(true)}>
              <Info className="h-4 w-4 mr-2" />
              Setup URLs
            </Button>
            <Button asChild size="sm" variant="default">
              <a href="/admin/integrations/sync">
                <RefreshCw className="h-4 w-4 mr-2" />
                Run Sync Now
              </a>
            </Button>
          </div>
        }
      />

      <IntegrationUrlsDocModal open={docsOpen} onOpenChange={setDocsOpen} />

      <Card>
        <CardHeader className="pb-3">
          <div className="flex items-center justify-between gap-3">
            <div className="flex items-center gap-2">
              <Activity className="h-4 w-4 text-muted-foreground" />
              <CardTitle className="text-base">Connection Health</CardTitle>
            </div>
            <Button variant="ghost" size="sm" onClick={load} disabled={loading}>
              <RefreshCw className={`h-3.5 w-3.5 mr-1.5 ${loading ? "animate-spin" : ""}`} />
              Refresh
            </Button>
          </div>
          <CardDescription>At-a-glance status for every provider. Click a tile to configure.</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
            {PROVIDERS.map((meta) => {
              const it = byProvider[meta.id];
              const status: Status = (it?.status as Status) ?? "disconnected";
              const enabled = !!it?.is_enabled;
              return (
                <button
                  key={`health-${meta.id}`}
                  type="button"
                  onClick={() => setOpenProvider(meta.id)}
                  className="text-left rounded-lg border bg-card p-3 transition-colors hover:bg-muted/50 focus:outline-none focus:ring-2 focus:ring-ring"
                >
                  <div className="flex items-center gap-3">
                    <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-md border bg-background p-1">
                      <img src={PROVIDER_LOGOS[meta.id]} alt="" className="h-full w-full object-contain" />
                    </div>
                    <div className="min-w-0 flex-1">
                      <div className="flex items-center justify-between gap-2">
                        <div className="font-medium text-sm truncate">{meta.name}</div>
                        {statusBadge(status)}
                      </div>
                      <div className="mt-1 flex items-center gap-2 text-xs text-muted-foreground">
                        <span className={`inline-block h-1.5 w-1.5 rounded-full ${enabled ? "bg-emerald-500" : "bg-muted-foreground/40"}`} />
                        <span>{enabled ? "Enabled" : "Disabled"}</span>
                        <span>•</span>
                        <span className="capitalize">{it?.environment ?? "sandbox"}</span>
                      </div>
                      <div className="mt-0.5 text-xs text-muted-foreground truncate">
                        {it?.last_error
                          ? <span className="text-destructive">{it.last_error}</span>
                          : <>Last sync: {it?.last_sync_at ? new Date(it.last_sync_at).toLocaleString() : "Never"}</>}
                      </div>
                    </div>
                  </div>
                </button>
              );
            })}
          </div>
        </CardContent>
      </Card>

      {loading ? (
        <div className="flex items-center justify-center py-16">
          <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
        </div>
      ) : (
        <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
          {PROVIDERS.map((meta) => {
            const it = byProvider[meta.id];
            const status: Status = (it?.status as Status) ?? "disconnected";
            const canAuthorizeQuickBooks = meta.id === "quickbooks" && Boolean(it?.has_credentials);
            const qboTokenExpired = meta.id === "quickbooks" && it?.token_expires_at
              ? new Date(it.token_expires_at).getTime() <= Date.now()
              : false;
            const qboNeedsReconnect = meta.id === "quickbooks" && (
              status === "error" || qboTokenExpired || (Boolean(it?.has_credentials) && status === "disconnected")
            );
            return (
              <Card key={meta.id} className="overflow-hidden transition-shadow hover:shadow-md">
                <div className="h-1.5" style={{ background: meta.brandColor }} />
                <CardHeader>
                  <div className="flex items-start justify-between gap-3">
                    <div className="flex items-start gap-3 min-w-0">
                      <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-lg border bg-background p-1.5">
                        <img
                          src={PROVIDER_LOGOS[meta.id]}
                          alt={`${meta.name} logo`}
                          width={48}
                          height={48}
                          loading="lazy"
                          className="h-full w-full object-contain"
                        />
                      </div>
                      <div className="min-w-0">
                        <CardTitle className="flex items-center gap-2">{meta.name}</CardTitle>
                        <CardDescription className="mt-1">{meta.tagline}</CardDescription>
                      </div>
                    </div>
                    {statusBadge(status)}
                  </div>
                </CardHeader>
                <CardContent className="space-y-3">
                  <div className="grid grid-cols-2 gap-3 text-xs">
                    <div className="rounded-md border bg-muted/30 px-2 py-1.5">
                      <div className="text-muted-foreground">Environment</div>
                      <div className="font-medium capitalize">{it?.environment ?? "sandbox"}</div>
                    </div>
                    <div className="rounded-md border bg-muted/30 px-2 py-1.5">
                      <div className="text-muted-foreground">Last sync</div>
                      <div className="font-medium">{it?.last_sync_at ? new Date(it.last_sync_at).toLocaleString() : "Never"}</div>
                    </div>
                  </div>

                  {it?.last_error && (
                    <div className="rounded-md border border-destructive/30 bg-destructive/5 px-3 py-2 text-xs text-destructive">
                      {it.last_error}
                    </div>
                  )}

                  <div className="flex flex-wrap gap-2 pt-2">
                    <Button size="sm" onClick={() => setOpenProvider(meta.id)}>
                      <ShieldCheck className="h-4 w-4 mr-1.5" />
                      {it?.has_credentials ? "Manage" : "Configure"}
                    </Button>
                    {canAuthorizeQuickBooks && (
                      <Button
                        size="sm"
                        variant={qboNeedsReconnect ? "destructive" : "default"}
                        disabled={busy === `${meta.id}:oauth`}
                        onClick={() => startOAuth(meta.id)}
                      >
                        {busy === `${meta.id}:oauth`
                          ? <Loader2 className="h-4 w-4 mr-1.5 animate-spin" />
                          : qboNeedsReconnect
                            ? <RefreshCw className="h-4 w-4 mr-1.5" />
                            : <ExternalLink className="h-4 w-4 mr-1.5" />}
                        {qboNeedsReconnect
                          ? (qboTokenExpired ? "Reconnect QuickBooks (token expired)" : "Reconnect QuickBooks")
                          : "Authorize QuickBooks"}
                      </Button>
                    )}
                    {status !== "connected" ? (
                      <Button
                        size="sm"
                        variant="default"
                        disabled={busy === `${meta.id}:connect`}
                        onClick={() => runAction(meta.id, "connect")}
                      >
                        {busy === `${meta.id}:connect` ? <Loader2 className="h-4 w-4 mr-1.5 animate-spin" /> : <Power className="h-4 w-4 mr-1.5" />}
                        Connect
                      </Button>
                    ) : (
                      <>
                        <Button size="sm" variant="outline" disabled={busy === `${meta.id}:test`} onClick={() => runAction(meta.id, "test")}>
                          {busy === `${meta.id}:test` ? <Loader2 className="h-4 w-4 mr-1.5 animate-spin" /> : <Activity className="h-4 w-4 mr-1.5" />}
                          Test
                        </Button>
                        <Button
                          size="sm"
                          variant="outline"
                          disabled={busy === `${meta.id}:disconnect`}
                          onClick={async () => {
                            const ok = await confirm({
                              title: "Disconnect integration?",
                              message: `This will remove all stored credentials for ${meta.name}. You can reconnect later.`,
                              confirmLabel: "Disconnect",
                              variant: "danger",
                            });
                            if (ok) runAction(meta.id, "disconnect");
                          }}
                        >
                          <Trash2 className="h-4 w-4 mr-1.5" />
                          Disconnect
                        </Button>
                      </>
                    )}
                    <a
                      href={meta.docsUrl}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="inline-flex items-center gap-1 text-xs text-muted-foreground hover:text-foreground self-center ml-auto"
                    >
                      Docs <ExternalLink className="h-3 w-3" />
                    </a>
                  </div>
                </CardContent>
              </Card>
            );
          })}
        </div>
      )}

      {openProvider && (
        <ProviderDialog
          provider={PROVIDERS.find((p) => p.id === openProvider)!}
          integration={byProvider[openProvider]}
          onClose={() => setOpenProvider(null)}
          onSaved={async () => { await load(); }}
          onSync={triggerSync}
          onStartOAuth={startOAuth}
          busy={busy}
        />
      )}
    </div>
  );
}

// ===========================================================================
// Provider configuration dialog (credentials + capabilities + logs + sync)
// ===========================================================================

function ProviderDialog({
  provider, integration, onClose, onSaved, onSync, onStartOAuth, busy,
}: {
  provider: ProviderMeta;
  integration?: Integration;
  onClose: () => void;
  onSaved: () => Promise<void>;
  onSync: (provider: ProviderId, entity: string) => Promise<void>;
  onStartOAuth: (provider: ProviderId) => Promise<void>;
  busy: string | null;
}) {
  const [environment, setEnvironment] = useState<"sandbox" | "production">(integration?.environment ?? "sandbox");
  const [enabled, setEnabled] = useState<boolean>(Boolean(integration?.is_enabled));
  const [creds, setCreds] = useState<Record<string, string>>({});
  const [config, setConfig] = useState<Record<string, boolean>>(() => {
    const out: Record<string, boolean> = {};
    provider.capabilities.forEach((c) => { out[c.key] = Boolean(integration?.config?.[c.key]); });
    return out;
  });
  const [showSecrets, setShowSecrets] = useState<Record<string, boolean>>({});
  const [saving, setSaving] = useState(false);
  const [logs, setLogs] = useState<IntegrationLog[]>([]);

  useEffect(() => {
    api.request<IntegrationLog[]>("GET", `integrations/${provider.id}/logs`)
      .then((res) => setLogs((res.data as IntegrationLog[]) ?? []))
      .catch(() => { /* non-blocking */ });
  }, [provider.id]);

  const save = async () => {
    try {
      setSaving(true);
      // Only send fields the user actually filled — preserves masked existing values
      const credsToSend: Record<string, string> = {};
      Object.entries(creds).forEach(([k, v]) => { if (v && v.trim() !== "") credsToSend[k] = v.trim(); });
      if (provider.id === "quickbooks") {
        credsToSend.redirect_uri = oauthCallbackUrl("quickbooks");
      }

      await api.request("PUT", `integrations/${provider.id}`, {
        display_name: provider.name,
        environment,
        is_enabled: enabled,
        credentials: credsToSend,
        config,
      });
      showSuccessToast("Integration saved");
      await onSaved();
    } catch (e: any) {
      showErrorToast(e?.message || "Failed to save");
    } finally {
      setSaving(false);
    }
  };

  return (
    <Dialog open onOpenChange={(o) => { if (!o) onClose(); }}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-3">
            <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-md border bg-background p-1">
              <img
                src={PROVIDER_LOGOS[provider.id]}
                alt={`${provider.name} logo`}
                width={36}
                height={36}
                loading="lazy"
                className="h-full w-full object-contain"
              />
            </div>
            <span>{provider.name}</span>
            {integration && statusBadge((integration.status as Status) ?? "disconnected")}
          </DialogTitle>
          <DialogDescription>{provider.tagline}</DialogDescription>
        </DialogHeader>

        <Tabs defaultValue="credentials" className="mt-2">
          <TabsList className="grid grid-cols-6 w-full">
            <TabsTrigger value="credentials">Credentials</TabsTrigger>
            <TabsTrigger value="features">Features</TabsTrigger>
            <TabsTrigger value="webhooks"><Webhook className="h-3.5 w-3.5 mr-1" />Webhooks</TabsTrigger>
            <TabsTrigger value="sync">Sync</TabsTrigger>
            <TabsTrigger value="logs">Logs</TabsTrigger>
            <TabsTrigger value="guide">Setup Guide</TabsTrigger>
          </TabsList>

          <TabsContent value="credentials" className="space-y-4 pt-4">
            <div className="grid grid-cols-2 gap-3">
              <div>
                <Label>Environment</Label>
                <Select value={environment} onValueChange={(v: any) => setEnvironment(v)}>
                  <SelectTrigger><SelectValue /></SelectTrigger>
                  <SelectContent>
                    <SelectItem value="sandbox">Sandbox</SelectItem>
                    <SelectItem value="production">Production</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="flex items-end gap-3">
                <div className="flex items-center gap-2">
                  <Switch checked={enabled} onCheckedChange={setEnabled} id="enabled" />
                  <Label htmlFor="enabled">Enabled</Label>
                </div>
              </div>
            </div>

            <div className="space-y-3">
              {provider.fields.map((f) => {
                const masked = (integration?.credentials as any)?.[f.key];
                const isSet = Boolean((integration?.credentials as any)?.[`${f.key}_set`] || (masked && typeof masked === "string"));
                const isQuickBooksRedirect = provider.id === "quickbooks" && f.key === "redirect_uri";
                const forcedRedirectUri = isQuickBooksRedirect ? oauthCallbackUrl("quickbooks") : "";
                return (
                  <div key={f.key} className="space-y-1.5">
                    <Label className="flex items-center justify-between">
                      <span>{f.label}</span>
                      {isSet && !isQuickBooksRedirect && <span className="text-[10px] text-muted-foreground">currently: {String(masked)}</span>}
                    </Label>
                    <div className="flex gap-2">
                      <Input
                        type={f.secret && !showSecrets[f.key] ? "password" : "text"}
                        value={isQuickBooksRedirect ? forcedRedirectUri : (creds[f.key] ?? "")}
                        onChange={(e) => {
                          if (!isQuickBooksRedirect) setCreds((p) => ({ ...p, [f.key]: e.target.value }));
                        }}
                        readOnly={isQuickBooksRedirect}
                        placeholder={f.placeholder ?? (isSet ? "Leave blank to keep existing" : "")}
                      />
                      {f.secret && (
                        <Button
                          type="button" variant="outline" size="icon"
                          onClick={() => setShowSecrets((p) => ({ ...p, [f.key]: !p[f.key] }))}
                        >
                          {showSecrets[f.key] ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
                        </Button>
                      )}
                    </div>
                    {f.helper && <p className="text-[11px] text-muted-foreground">{f.helper}</p>}
                    {isQuickBooksRedirect && (
                      <p className="text-[11px] text-warning-foreground">
                        In Intuit, add this exact URI under {environment === "sandbox" ? "Development settings" : "Production settings"} for the same Client ID you saved here.
                      </p>
                    )}
                  </div>
                );
              })}
            </div>
          </TabsContent>

          <TabsContent value="features" className="space-y-3 pt-4">
            <p className="text-sm text-muted-foreground">Toggle which data flows are active for this integration.</p>
            {provider.capabilities.map((c) => (
              <div key={c.key} className="flex items-center justify-between rounded-md border p-3">
                <Label htmlFor={c.key} className="font-normal">{c.label}</Label>
                <Switch
                  id={c.key}
                  checked={Boolean(config[c.key])}
                  onCheckedChange={(v) => setConfig((p) => ({ ...p, [c.key]: v }))}
                />
              </div>
            ))}
          </TabsContent>

          <TabsContent value="webhooks" className="space-y-4 pt-4">
            <WebhookPanel providerId={provider.id} environment={environment} />
          </TabsContent>

          <TabsContent value="sync" className="space-y-3 pt-4">
            {integration?.status !== "connected" ? (
              <div className="rounded-md border border-warning/30 bg-warning/5 p-4 text-sm text-warning-foreground">
                Connect this integration first to enable syncing.
              </div>
            ) : (
              <>
                <p className="text-sm text-muted-foreground">Trigger a one-time sync for the selected entity.</p>
                <div className="grid gap-2">
                  {provider.syncEntities.map((entity) => (
                    <div key={entity.key} className="flex items-center justify-between rounded-md border p-3">
                      <span className="text-sm">{entity.label}</span>
                      <Button
                        size="sm"
                        variant="outline"
                        disabled={busy === `${provider.id}:sync:${entity.key}`}
                        onClick={() => onSync(provider.id, entity.key)}
                      >
                        {busy === `${provider.id}:sync:${entity.key}`
                          ? <Loader2 className="h-4 w-4 mr-1.5 animate-spin" />
                          : <RefreshCw className="h-4 w-4 mr-1.5" />}
                        Sync now
                      </Button>
                    </div>
                  ))}
                </div>
              </>
            )}
          </TabsContent>

          <TabsContent value="logs" className="pt-4">
            {logs.length === 0 ? (
              <p className="text-sm text-muted-foreground">No activity yet.</p>
            ) : (
              <div className="space-y-2 max-h-72 overflow-y-auto">
                {logs.map((l) => (
                  <div key={l.id} className="flex items-start gap-2 rounded-md border p-2 text-xs">
                    <Badge variant={l.status === "error" ? "destructive" : l.status === "warning" ? "outline" : "secondary"}>
                      {l.action}
                    </Badge>
                    <div className="flex-1 min-w-0">
                      <div className="truncate">{l.message ?? "—"}</div>
                      <div className="text-[10px] text-muted-foreground">
                        {new Date(l.created_at).toLocaleString()}
                        {l.duration_ms != null && ` · ${l.duration_ms}ms`}
                        {l.items_processed != null && ` · ${l.items_processed} processed`}
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </TabsContent>

          <TabsContent value="guide" className="pt-4">
            <SetupGuide providerId={provider.id} />
          </TabsContent>
        </Tabs>

        <DialogFooter className="gap-2">
          <Button variant="outline" onClick={onClose}>Close</Button>
          {provider.id === "quickbooks" && integration?.has_credentials && (
            <Button
              variant="default"
              onClick={() => onStartOAuth(provider.id)}
              disabled={busy === `${provider.id}:oauth`}
            >
              {busy === `${provider.id}:oauth` ? <Loader2 className="h-4 w-4 mr-1.5 animate-spin" /> : <ExternalLink className="h-4 w-4 mr-1.5" />}
              Authorize QuickBooks
            </Button>
          )}
          <Button onClick={save} disabled={saving}>
            {saving ? <Loader2 className="h-4 w-4 mr-1.5 animate-spin" /> : <Save className="h-4 w-4 mr-1.5" />}
            Save
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// ===========================================================================
// Webhook URLs panel — shows the exact callback URLs to paste into each
// provider's developer console. URLs are derived live from the running
// host so dev / staging / production each show their own correct values.
// ===========================================================================

interface WebhookEndpoint {
  label: string;
  description: string;
  url: string;
  copyHint?: string;
}

function buildWebhookEndpoints(providerId: ProviderId): {
  endpoints: WebhookEndpoint[];
  notes: { title: string; body: string; href?: string }[];
} {
  // Backend folder containing api.php (e.g. https://luccibyey.com.tn/remquip/backend)
  const apiBase = API_BASE_URL.replace(/\/+$/, "");

  const oauthCallback = oauthCallbackUrl(providerId);
  const webhookUrl    = `${apiBase}/api.php?path=integrations/${providerId}/webhook`;

  if (providerId === "quickbooks") {
    return {
      endpoints: [
        {
          label: "OAuth Redirect URI",
          description: "Paste in Intuit App → Keys & OAuth → Redirect URIs.",
          url: oauthCallback,
          copyHint: "Must match EXACTLY what you put in the Credentials tab.",
        },
        {
          label: "Webhook Notification URL",
          description: "Paste in Intuit App → Webhooks → Endpoint URL.",
          url: webhookUrl,
          copyHint: "Intuit will POST entity-change events here.",
        },
      ],
      notes: [
        {
          title: "Verifier Token (HMAC-SHA256)",
          body: "After saving the Webhook URL, Intuit gives you a Verifier Token. Save it in the Credentials tab as `webhook_verifier_token` so signature validation works.",
          href: "https://developer.intuit.com/app/developer/qbo/docs/develop/webhooks",
        },
      ],
    };
  }

  if (providerId === "amazon") {
    return {
      endpoints: [
        {
          label: "OAuth Redirect URI (LWA)",
          description: "Paste in Seller Central → Apps & Services → Develop Apps → Edit App → Login Redirect URI.",
          url: oauthCallback,
        },
        {
          label: "SQS / SNS Notification Endpoint",
          description: "Public endpoint that receives Amazon Notifications API events (forwarded from your SQS/SNS).",
          url: webhookUrl,
          copyHint: "Subscribe your SQS queue to publish to this URL via SNS HTTPS subscription.",
        },
      ],
      notes: [
        {
          title: "Notifications API setup",
          body: "Amazon doesn't push directly to your URL — you create a destination (SQS) and subscribe to notification types (ANY_OFFER_CHANGED, ORDER_CHANGE, etc.). Bridge SQS → this webhook URL via SNS or a poller.",
          href: "https://developer-docs.amazon.com/sp-api/docs/notifications-api-v1-use-case-guide",
        },
      ],
    };
  }

  // eBay
  const accountDeletionUrl = `${apiBase}/api.php?path=integrations/ebay/webhook`;
  return {
    endpoints: [
      {
        label: "OAuth RuName Redirect",
        description: "Paste in eBay Developer → Application Keysets → User Tokens → Your Branded Sign In.",
        url: oauthCallback,
        copyHint: "eBay will return the user here after consent — the page captures the auth code.",
      },
      {
        label: "Marketplace Account Deletion endpoint (REQUIRED)",
        description: "Paste in eBay Developer → Application Keysets → Notifications → Marketplace Account Deletion.",
        url: accountDeletionUrl,
        copyHint: "eBay will GET this URL with ?challenge_code=... — backend responds with the SHA-256 hash automatically.",
      },
      {
        label: "Platform Notifications endpoint",
        description: "Paste in eBay Developer → Notifications → Platform Notifications (for order/listing events).",
        url: webhookUrl,
      },
    ],
    notes: [
      {
        title: "Verification Token",
        body: "After saving the Account Deletion endpoint, copy the Verification Token eBay generates and store it in the Credentials tab as `webhook_verification_token`.",
        href: "https://developer.ebay.com/marketplace-account-deletion",
      },
    ],
  };
}

function WebhookPanel({ providerId, environment }: { providerId: ProviderId; environment: "sandbox" | "production" }) {
  const { endpoints, notes } = useMemo(() => buildWebhookEndpoints(providerId), [providerId]);

  return (
    <div className="space-y-4">
      <div className="rounded-md border border-primary/20 bg-primary/5 p-3 text-xs">
        <p className="font-medium text-foreground mb-1">📌 Configure these URLs in the provider's developer console</p>
        <p className="text-muted-foreground">
          Copy the URLs below and paste them into the matching fields in {providerId === "quickbooks" ? "Intuit Developer" : providerId === "amazon" ? "Amazon Seller Central / SP-API" : "eBay Developer Program"}. OAuth redirects use the canonical app URL, so they stay stable even when you manage this page from a preview URL.
          {providerId === "quickbooks" ? ` Use Intuit's ${environment === "sandbox" ? "Development settings" : "Production settings"} tab for the Client ID saved in Credentials.` : ""}
        </p>
      </div>

      <div className="space-y-3">
        {endpoints.map((ep) => (
          <div key={ep.label} className="rounded-md border p-3 space-y-2">
            <div className="flex items-start justify-between gap-2">
              <div className="min-w-0">
                <div className="text-sm font-medium">{ep.label}</div>
                <p className="text-xs text-muted-foreground mt-0.5">{ep.description}</p>
              </div>
            </div>
            <CopyableUrl value={ep.url} />
            {ep.copyHint && (
              <p className="text-[11px] text-muted-foreground italic">{ep.copyHint}</p>
            )}
          </div>
        ))}
      </div>

      {notes.length > 0 && (
        <div className="space-y-2">
          {notes.map((n) => (
            <div key={n.title} className="rounded-md border border-warning/30 bg-warning/5 p-3 text-xs">
              <div className="font-medium mb-1 flex items-center gap-1">
                <AlertTriangle className="h-3.5 w-3.5" />
                {n.title}
              </div>
              <p className="text-muted-foreground">{n.body}</p>
              {n.href && (
                <a
                  href={n.href}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-1 mt-1.5 text-foreground hover:underline"
                >
                  Read docs <ExternalLink className="h-3 w-3" />
                </a>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

function CopyableUrl({ value }: { value: string }) {
  const [copied, setCopied] = useState(false);

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(value);
      setCopied(true);
      showSuccessToast("URL copied to clipboard");
      setTimeout(() => setCopied(false), 1800);
    } catch {
      showErrorToast("Could not copy to clipboard");
    }
  };

  return (
    <div className="flex gap-2">
      <Input value={value} readOnly className="font-mono text-xs" onFocus={(e) => e.currentTarget.select()} />
      <Button type="button" size="icon" variant="outline" onClick={copy} aria-label="Copy URL">
        {copied ? <Check className="h-4 w-4 text-success" /> : <Copy className="h-4 w-4" />}
      </Button>
    </div>
  );
}

// ===========================================================================
// Setup Guide — exhaustive step-by-step checklist per provider so an admin
// can go from "no account" to a fully working sync without leaving this page.
// ===========================================================================

interface GuideStep {
  title: string;
  body: React.ReactNode;
}

function SetupGuide({ providerId }: { providerId: ProviderId }) {
  const steps: GuideStep[] = useMemo(() => buildGuide(providerId), [providerId]);

  return (
    <div className="space-y-3 max-h-[60vh] overflow-y-auto pr-1">
      <div className="rounded-md border border-primary/20 bg-primary/5 p-3 text-xs">
        <p className="font-medium mb-1">Complete checklist — follow top to bottom</p>
        <p className="text-muted-foreground">
          You only need to do these steps once per environment. After the last step the integration will sync automatically.
        </p>
      </div>
      <ol className="space-y-2">
        {steps.map((s, i) => (
          <li key={s.title} className="rounded-md border p-3">
            <div className="flex items-start gap-3">
              <div className="flex-shrink-0 w-6 h-6 rounded-full bg-primary/10 text-primary text-xs font-bold flex items-center justify-center mt-0.5">
                {i + 1}
              </div>
              <div className="min-w-0 flex-1">
                <div className="text-sm font-medium mb-1">{s.title}</div>
                <div className="text-xs text-muted-foreground space-y-1">{s.body}</div>
              </div>
            </div>
          </li>
        ))}
      </ol>
    </div>
  );
}

function ExtLink({ href, children }: { href: string; children: React.ReactNode }) {
  return (
    <a href={href} target="_blank" rel="noopener noreferrer" className="text-foreground underline inline-flex items-center gap-1">
      {children} <ExternalLink className="h-3 w-3" />
    </a>
  );
}

function buildGuide(providerId: ProviderId): GuideStep[] {
  if (providerId === "quickbooks") {
    return [
      {
        title: "Create an Intuit developer account",
        body: <>Sign up at <ExtLink href="https://developer.intuit.com/app/developer/qbo/docs/get-started">developer.intuit.com</ExtLink>. Free.</>,
      },
      {
        title: "Create an App and get keys",
        body: <>In the dashboard → <strong>My Apps → Create an app → QuickBooks Online and Payments</strong>. Open the app → <strong>Keys & OAuth</strong>. Copy <code>Client ID</code> and <code>Client Secret</code> (use the <em>Sandbox</em> set first to test).</>,
      },
      {
        title: "Add the Redirect URI",
        body: <>In <strong>Keys & OAuth → Redirect URIs</strong> paste the URL shown in the <strong>Webhooks</strong> tab here (it ends with <code>/admin/integrations/oauth/quickbooks</code>). Save.</>,
      },
      {
        title: "Paste credentials in the Credentials tab",
        body: <>Open the <strong>Credentials</strong> tab here, paste <code>Client ID</code>, <code>Client Secret</code>, <code>Redirect URI</code>. Set environment to <em>Sandbox</em> while testing. Save.</>,
      },
      {
        title: "Run the OAuth flow",
        body: <>Click <strong>Connect</strong> on the card — you'll be redirected to Intuit, sign in with the test company, click Authorize. The callback page captures the <code>code</code>, <code>state</code> and <code>realmId</code> automatically and saves the access + refresh tokens.</>,
      },
      {
        title: "Configure the Webhook",
        body: <>In Intuit Developer → <strong>Webhooks</strong>, paste the Webhook URL from the Webhooks tab here. Tick the entities you care about (Customer, Invoice, Payment, Item). Intuit will display a <strong>Verifier Token</strong> — copy it.</>,
      },
      {
        title: "Save the Verifier Token",
        body: <>Back in the <strong>Credentials</strong> tab here, paste it into <code>Webhook Verifier Token</code>. Without this, our backend will reject every webhook with HTTP 401.</>,
      },
      {
        title: "Test & sync",
        body: <>Click <strong>Test</strong> on the card — should ping <code>CompanyInfo</code> successfully. Then open <strong>Sync</strong> tab and trigger an entity sync.</>,
      },
      {
        title: "Go to Production",
        body: <>Get your app reviewed by Intuit (required for production). Switch the environment toggle to <em>Production</em>, paste the Production keys, and re-run the OAuth flow against the live company.</>,
      },
    ];
  }

  if (providerId === "amazon") {
    return [
      {
        title: "Become an Amazon SP-API developer",
        body: <>Register as a developer in <ExtLink href="https://sellercentral.amazon.com/sellingpartner/developerconsole">Seller Central → Developer Console</ExtLink>. Approval can take a few days for production.</>,
      },
      {
        title: "Create a Login With Amazon (LWA) app",
        body: <>In Developer Console, create a new SP-API app. Take note of <code>LWA Client ID</code> and <code>LWA Client Secret</code>. Add the Login Redirect URI shown in our Webhooks tab.</>,
      },
      {
        title: "Authorize the app for your seller account",
        body: <>Use the Self-Authorize flow in Developer Console (for your own account) or the Marketplace Authorization Workflow (for third parties). This produces a <code>Refresh Token</code>.</>,
      },
      {
        title: "Pick the right Marketplace ID",
        body: <>Find yours in the <ExtLink href="https://developer-docs.amazon.com/sp-api/docs/marketplace-ids">Marketplace IDs reference</ExtLink>. Common: <code>ATVPDKIKX0DER</code> (US), <code>A1F83G8C2ARO7P</code> (UK), <code>A13V1IB3VIYZZH</code> (FR).</>,
      },
      {
        title: "Paste credentials & connect",
        body: <>Fill <code>LWA Client ID</code>, <code>LWA Client Secret</code>, <code>Refresh Token</code>, <code>Seller ID</code>, <code>Marketplace ID</code> in the Credentials tab. Click <strong>Connect</strong>.</>,
      },
      {
        title: "Set up Notifications (orders, listings)",
        body: <>SP-API does not push to your URL directly — instead create a destination in <strong>Notifications API</strong> (SQS queue) and subscribe to <code>ORDER_CHANGE</code>, <code>ANY_OFFER_CHANGED</code>, etc. Bridge SQS → our webhook URL via SNS HTTPS subscription or a small worker. Docs: <ExtLink href="https://developer-docs.amazon.com/sp-api/docs/notifications-api-v1-use-case-guide">Notifications guide</ExtLink>.</>,
      },
      {
        title: "Restricted Data Token (RDT) for PII",
        body: <>To read buyer info, addresses or PII you must call the <ExtLink href="https://developer-docs.amazon.com/sp-api/docs/tokens-api-v2021-03-01-reference">Tokens API</ExtLink> first to get a Restricted Data Token, then pass it as <code>x-amz-access-token</code>.</>,
      },
      {
        title: "Test & sync",
        body: <>Hit <strong>Test</strong> (calls <code>getMarketplaceParticipations</code>). Then trigger Orders / Listings / Inventory sync.</>,
      },
    ];
  }

  // eBay
  return [
    {
      title: "Create an eBay developer account",
      body: <>Sign up at <ExtLink href="https://developer.ebay.com">developer.ebay.com</ExtLink>. Apply for a Production keyset (sandbox is automatic).</>,
    },
    {
      title: "Get an Application Keyset",
      body: <>Application Keys page → copy <code>App ID</code>, <code>Cert ID</code>, <code>Dev ID</code>. Two sets are issued: Sandbox and Production.</>,
    },
    {
      title: "Create a RuName (Redirect URL Name)",
      body: <>User Tokens → <strong>Get a Token from eBay via Your Application</strong> → <strong>Add eBay Redirect URL</strong>. Use the Redirect URL shown in the Webhooks tab (<code>/admin/integrations/oauth/ebay</code>). eBay returns a RuName — paste it as <code>Redirect URI</code> in the Credentials tab.</>,
    },
    {
      title: "Run the user consent flow",
      body: <>From your account, accept the consent prompt with scope <code>https://api.ebay.com/oauth/api_scope</code> + the Sell scopes you need (<code>sell.inventory</code>, <code>sell.fulfillment</code>, <code>sell.account</code>) and <code>offline_access</code>. eBay returns an authorization code — exchanged for an 18-month refresh token, saved automatically by the callback page.</>,
    },
    {
      title: "Set up Marketplace Account Deletion (REQUIRED for production)",
      body: <>Notifications page → <strong>Marketplace Account Deletion / Closure Notifications</strong>. Paste the <em>Account Deletion endpoint</em> URL from the Webhooks tab. Generate a long random string for <strong>Verification Token</strong> (32–80 chars), paste it both into eBay and into <code>Webhook Verification Token</code> in our Credentials tab. eBay will GET the URL with <code>?challenge_code=…</code> — our backend replies with the SHA-256 hash automatically.</>,
    },
    {
      title: "Subscribe to Platform Notifications",
      body: <>For order / listing events, subscribe to platform notifications and point them at the Webhook URL from the Webhooks tab. Each POST is signed with <code>x-ebay-signature</code> — our backend verifies it using the same Verification Token.</>,
    },
    {
      title: "Test & sync",
      body: <>Hit <strong>Test</strong> (calls <code>getPrivileges</code>). Trigger an Inventory or Orders sync. Refresh tokens auto-renew the 2-hour access tokens.</>,
    },
  ];
}
